#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosLinqEscolar.Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="escolaruv")]
	public partial class DataClassesEscolarUVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertacademico(academico instance);
    partial void Updateacademico(academico instance);
    partial void Deleteacademico(academico instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    partial void Insertalumno(alumno instance);
    partial void Updatealumno(alumno instance);
    partial void Deletealumno(alumno instance);
    partial void Insertcarrera(carrera instance);
    partial void Updatecarrera(carrera instance);
    partial void Deletecarrera(carrera instance);
    partial void Insertfacultad(facultad instance);
    partial void Updatefacultad(facultad instance);
    partial void Deletefacultad(facultad instance);
    #endregion
		
		public DataClassesEscolarUVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesEscolarUVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesEscolarUVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesEscolarUVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<academico> academico
		{
			get
			{
				return this.GetTable<academico>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<alumno> alumno
		{
			get
			{
				return this.GetTable<alumno>();
			}
		}
		
		public System.Data.Linq.Table<carrera> carrera
		{
			get
			{
				return this.GetTable<carrera>();
			}
		}
		
		public System.Data.Linq.Table<facultad> facultad
		{
			get
			{
				return this.GetTable<facultad>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.academico")]
	public partial class academico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAcademico;
		
		private string _nombre;
		
		private string _apellidoPaterno;
		
		private string _apellidoMaterno;
		
		private string _correoInstitucional;
		
		private string _matricula;
		
		private string _numeroTelefonico;
		
		private string _rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAcademicoChanging(int value);
    partial void OnidAcademicoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoPaternoChanging(string value);
    partial void OnapellidoPaternoChanged();
    partial void OnapellidoMaternoChanging(string value);
    partial void OnapellidoMaternoChanged();
    partial void OncorreoInstitucionalChanging(string value);
    partial void OncorreoInstitucionalChanged();
    partial void OnmatriculaChanging(string value);
    partial void OnmatriculaChanged();
    partial void OnnumeroTelefonicoChanging(string value);
    partial void OnnumeroTelefonicoChanged();
    partial void OnrolChanging(string value);
    partial void OnrolChanged();
    #endregion
		
		public academico()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAcademico", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idAcademico
		{
			get
			{
				return this._idAcademico;
			}
			set
			{
				if ((this._idAcademico != value))
				{
					this.OnidAcademicoChanging(value);
					this.SendPropertyChanging();
					this._idAcademico = value;
					this.SendPropertyChanged("idAcademico");
					this.OnidAcademicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoPaterno", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string apellidoPaterno
		{
			get
			{
				return this._apellidoPaterno;
			}
			set
			{
				if ((this._apellidoPaterno != value))
				{
					this.OnapellidoPaternoChanging(value);
					this.SendPropertyChanging();
					this._apellidoPaterno = value;
					this.SendPropertyChanged("apellidoPaterno");
					this.OnapellidoPaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoMaterno", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string apellidoMaterno
		{
			get
			{
				return this._apellidoMaterno;
			}
			set
			{
				if ((this._apellidoMaterno != value))
				{
					this.OnapellidoMaternoChanging(value);
					this.SendPropertyChanging();
					this._apellidoMaterno = value;
					this.SendPropertyChanged("apellidoMaterno");
					this.OnapellidoMaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoInstitucional", DbType="VarChar(50)")]
		public string correoInstitucional
		{
			get
			{
				return this._correoInstitucional;
			}
			set
			{
				if ((this._correoInstitucional != value))
				{
					this.OncorreoInstitucionalChanging(value);
					this.SendPropertyChanging();
					this._correoInstitucional = value;
					this.SendPropertyChanged("correoInstitucional");
					this.OncorreoInstitucionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="VarChar(25)")]
		public string matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					this.OnmatriculaChanging(value);
					this.SendPropertyChanging();
					this._matricula = value;
					this.SendPropertyChanged("matricula");
					this.OnmatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroTelefonico", DbType="VarChar(9)")]
		public string numeroTelefonico
		{
			get
			{
				return this._numeroTelefonico;
			}
			set
			{
				if ((this._numeroTelefonico != value))
				{
					this.OnnumeroTelefonicoChanging(value);
					this.SendPropertyChanging();
					this._numeroTelefonico = value;
					this.SendPropertyChanged("numeroTelefonico");
					this.OnnumeroTelefonicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="VarChar(100)")]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this.OnrolChanging(value);
					this.SendPropertyChanging();
					this._rol = value;
					this.SendPropertyChanged("rol");
					this.OnrolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private string _nombre;
		
		private string _apellidoPaterno;
		
		private string _apellidoMaterno;
		
		private string _username;
		
		private string _password;
		
		private string _correoInstitucional;
		
		private string _matricula;
		
		private string _numeroTelefonico;
		
		private string _rol;
		
		private EntitySet<alumno> _alumno;
		
		private EntitySet<carrera> _carrera;
		
		private EntitySet<carrera> _carrera1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoPaternoChanging(string value);
    partial void OnapellidoPaternoChanged();
    partial void OnapellidoMaternoChanging(string value);
    partial void OnapellidoMaternoChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OncorreoInstitucionalChanging(string value);
    partial void OncorreoInstitucionalChanged();
    partial void OnmatriculaChanging(string value);
    partial void OnmatriculaChanged();
    partial void OnnumeroTelefonicoChanging(string value);
    partial void OnnumeroTelefonicoChanged();
    partial void OnrolChanging(string value);
    partial void OnrolChanged();
    #endregion
		
		public usuario()
		{
			this._alumno = new EntitySet<alumno>(new Action<alumno>(this.attach_alumno), new Action<alumno>(this.detach_alumno));
			this._carrera = new EntitySet<carrera>(new Action<carrera>(this.attach_carrera), new Action<carrera>(this.detach_carrera));
			this._carrera1 = new EntitySet<carrera>(new Action<carrera>(this.attach_carrera1), new Action<carrera>(this.detach_carrera1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(500)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoPaterno", DbType="VarChar(255)")]
		public string apellidoPaterno
		{
			get
			{
				return this._apellidoPaterno;
			}
			set
			{
				if ((this._apellidoPaterno != value))
				{
					this.OnapellidoPaternoChanging(value);
					this.SendPropertyChanging();
					this._apellidoPaterno = value;
					this.SendPropertyChanged("apellidoPaterno");
					this.OnapellidoPaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoMaterno", DbType="VarChar(255)")]
		public string apellidoMaterno
		{
			get
			{
				return this._apellidoMaterno;
			}
			set
			{
				if ((this._apellidoMaterno != value))
				{
					this.OnapellidoMaternoChanging(value);
					this.SendPropertyChanging();
					this._apellidoMaterno = value;
					this.SendPropertyChanged("apellidoMaterno");
					this.OnapellidoMaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(20)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoInstitucional", DbType="VarChar(50)")]
		public string correoInstitucional
		{
			get
			{
				return this._correoInstitucional;
			}
			set
			{
				if ((this._correoInstitucional != value))
				{
					this.OncorreoInstitucionalChanging(value);
					this.SendPropertyChanging();
					this._correoInstitucional = value;
					this.SendPropertyChanged("correoInstitucional");
					this.OncorreoInstitucionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="VarChar(25)")]
		public string matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					this.OnmatriculaChanging(value);
					this.SendPropertyChanging();
					this._matricula = value;
					this.SendPropertyChanged("matricula");
					this.OnmatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroTelefonico", DbType="VarChar(9)")]
		public string numeroTelefonico
		{
			get
			{
				return this._numeroTelefonico;
			}
			set
			{
				if ((this._numeroTelefonico != value))
				{
					this.OnnumeroTelefonicoChanging(value);
					this.SendPropertyChanging();
					this._numeroTelefonico = value;
					this.SendPropertyChanged("numeroTelefonico");
					this.OnnumeroTelefonicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="VarChar(50)")]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this.OnrolChanging(value);
					this.SendPropertyChanging();
					this._rol = value;
					this.SendPropertyChanged("rol");
					this.OnrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_alumno", Storage="_alumno", ThisKey="idUsuario", OtherKey="idTutor")]
		public EntitySet<alumno> alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_carrera", Storage="_carrera", ThisKey="idUsuario", OtherKey="idCoordinadorTutorias")]
		public EntitySet<carrera> carrera
		{
			get
			{
				return this._carrera;
			}
			set
			{
				this._carrera.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_carrera1", Storage="_carrera1", ThisKey="idUsuario", OtherKey="idJefeCarrera")]
		public EntitySet<carrera> carrera1
		{
			get
			{
				return this._carrera1;
			}
			set
			{
				this._carrera1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_alumno(alumno entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_alumno(alumno entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_carrera(carrera entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_carrera(carrera entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_carrera1(carrera entity)
		{
			this.SendPropertyChanging();
			entity.usuario1 = this;
		}
		
		private void detach_carrera1(carrera entity)
		{
			this.SendPropertyChanging();
			entity.usuario1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumno")]
	public partial class alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAlumno;
		
		private string _nombre;
		
		private string _apellidoPaterno;
		
		private string _apellidoMaterno;
		
		private string _matricula;
		
		private string _correo;
		
		private System.Nullable<System.DateTime> _fechaNacimiento;
		
		private System.Data.Linq.Binary _foto;
		
		private System.Nullable<int> _idCarrera;
		
		private System.Nullable<int> _idTutor;
		
		private EntityRef<usuario> _usuario;
		
		private EntityRef<carrera> _carrera;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAlumnoChanging(int value);
    partial void OnidAlumnoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoPaternoChanging(string value);
    partial void OnapellidoPaternoChanged();
    partial void OnapellidoMaternoChanging(string value);
    partial void OnapellidoMaternoChanged();
    partial void OnmatriculaChanging(string value);
    partial void OnmatriculaChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnfechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaNacimientoChanged();
    partial void OnfotoChanging(System.Data.Linq.Binary value);
    partial void OnfotoChanged();
    partial void OnidCarreraChanging(System.Nullable<int> value);
    partial void OnidCarreraChanged();
    partial void OnidTutorChanging(System.Nullable<int> value);
    partial void OnidTutorChanged();
    #endregion
		
		public alumno()
		{
			this._usuario = default(EntityRef<usuario>);
			this._carrera = default(EntityRef<carrera>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAlumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idAlumno
		{
			get
			{
				return this._idAlumno;
			}
			set
			{
				if ((this._idAlumno != value))
				{
					this.OnidAlumnoChanging(value);
					this.SendPropertyChanging();
					this._idAlumno = value;
					this.SendPropertyChanged("idAlumno");
					this.OnidAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoPaterno", DbType="VarChar(255)")]
		public string apellidoPaterno
		{
			get
			{
				return this._apellidoPaterno;
			}
			set
			{
				if ((this._apellidoPaterno != value))
				{
					this.OnapellidoPaternoChanging(value);
					this.SendPropertyChanging();
					this._apellidoPaterno = value;
					this.SendPropertyChanged("apellidoPaterno");
					this.OnapellidoPaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoMaterno", DbType="VarChar(255)")]
		public string apellidoMaterno
		{
			get
			{
				return this._apellidoMaterno;
			}
			set
			{
				if ((this._apellidoMaterno != value))
				{
					this.OnapellidoMaternoChanging(value);
					this.SendPropertyChanging();
					this._apellidoMaterno = value;
					this.SendPropertyChanged("apellidoMaterno");
					this.OnapellidoMaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricula", DbType="VarChar(25)")]
		public string matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				if ((this._matricula != value))
				{
					this.OnmatriculaChanging(value);
					this.SendPropertyChanging();
					this._matricula = value;
					this.SendPropertyChanged("matricula");
					this.OnmatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this.OnfechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaNacimiento = value;
					this.SendPropertyChanged("fechaNacimiento");
					this.OnfechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarrera", DbType="Int")]
		public System.Nullable<int> idCarrera
		{
			get
			{
				return this._idCarrera;
			}
			set
			{
				if ((this._idCarrera != value))
				{
					if (this._carrera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCarreraChanging(value);
					this.SendPropertyChanging();
					this._idCarrera = value;
					this.SendPropertyChanged("idCarrera");
					this.OnidCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTutor", DbType="Int")]
		public System.Nullable<int> idTutor
		{
			get
			{
				return this._idTutor;
			}
			set
			{
				if ((this._idTutor != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTutorChanging(value);
					this.SendPropertyChanging();
					this._idTutor = value;
					this.SendPropertyChanged("idTutor");
					this.OnidTutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_alumno", Storage="_usuario", ThisKey="idTutor", OtherKey="idUsuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.alumno.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.alumno.Add(this);
						this._idTutor = value.idUsuario;
					}
					else
					{
						this._idTutor = default(Nullable<int>);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrera_alumno", Storage="_carrera", ThisKey="idCarrera", OtherKey="idCarrera", IsForeignKey=true)]
		public carrera carrera
		{
			get
			{
				return this._carrera.Entity;
			}
			set
			{
				carrera previousValue = this._carrera.Entity;
				if (((previousValue != value) 
							|| (this._carrera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carrera.Entity = null;
						previousValue.alumno.Remove(this);
					}
					this._carrera.Entity = value;
					if ((value != null))
					{
						value.alumno.Add(this);
						this._idCarrera = value.idCarrera;
					}
					else
					{
						this._idCarrera = default(Nullable<int>);
					}
					this.SendPropertyChanged("carrera");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrera")]
	public partial class carrera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCarrera;
		
		private string _nombre;
		
		private string _codigo;
		
		private System.Nullable<int> _idFacultad;
		
		private System.Nullable<int> _idCoordinadorTutorias;
		
		private System.Nullable<int> _idJefeCarrera;
		
		private EntitySet<alumno> _alumno;
		
		private EntityRef<usuario> _usuario;
		
		private EntityRef<usuario> _usuario1;
		
		private EntityRef<facultad> _facultad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCarreraChanging(int value);
    partial void OnidCarreraChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnidFacultadChanging(System.Nullable<int> value);
    partial void OnidFacultadChanged();
    partial void OnidCoordinadorTutoriasChanging(System.Nullable<int> value);
    partial void OnidCoordinadorTutoriasChanged();
    partial void OnidJefeCarreraChanging(System.Nullable<int> value);
    partial void OnidJefeCarreraChanged();
    #endregion
		
		public carrera()
		{
			this._alumno = new EntitySet<alumno>(new Action<alumno>(this.attach_alumno), new Action<alumno>(this.detach_alumno));
			this._usuario = default(EntityRef<usuario>);
			this._usuario1 = default(EntityRef<usuario>);
			this._facultad = default(EntityRef<facultad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarrera", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCarrera
		{
			get
			{
				return this._idCarrera;
			}
			set
			{
				if ((this._idCarrera != value))
				{
					this.OnidCarreraChanging(value);
					this.SendPropertyChanging();
					this._idCarrera = value;
					this.SendPropertyChanged("idCarrera");
					this.OnidCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(10)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFacultad", DbType="Int")]
		public System.Nullable<int> idFacultad
		{
			get
			{
				return this._idFacultad;
			}
			set
			{
				if ((this._idFacultad != value))
				{
					if (this._facultad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidFacultadChanging(value);
					this.SendPropertyChanging();
					this._idFacultad = value;
					this.SendPropertyChanged("idFacultad");
					this.OnidFacultadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCoordinadorTutorias", DbType="Int")]
		public System.Nullable<int> idCoordinadorTutorias
		{
			get
			{
				return this._idCoordinadorTutorias;
			}
			set
			{
				if ((this._idCoordinadorTutorias != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCoordinadorTutoriasChanging(value);
					this.SendPropertyChanging();
					this._idCoordinadorTutorias = value;
					this.SendPropertyChanged("idCoordinadorTutorias");
					this.OnidCoordinadorTutoriasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJefeCarrera", DbType="Int")]
		public System.Nullable<int> idJefeCarrera
		{
			get
			{
				return this._idJefeCarrera;
			}
			set
			{
				if ((this._idJefeCarrera != value))
				{
					if (this._usuario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidJefeCarreraChanging(value);
					this.SendPropertyChanging();
					this._idJefeCarrera = value;
					this.SendPropertyChanged("idJefeCarrera");
					this.OnidJefeCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrera_alumno", Storage="_alumno", ThisKey="idCarrera", OtherKey="idCarrera")]
		public EntitySet<alumno> alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_carrera", Storage="_usuario", ThisKey="idCoordinadorTutorias", OtherKey="idUsuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.carrera.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.carrera.Add(this);
						this._idCoordinadorTutorias = value.idUsuario;
					}
					else
					{
						this._idCoordinadorTutorias = default(Nullable<int>);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_carrera1", Storage="_usuario1", ThisKey="idJefeCarrera", OtherKey="idUsuario", IsForeignKey=true)]
		public usuario usuario1
		{
			get
			{
				return this._usuario1.Entity;
			}
			set
			{
				usuario previousValue = this._usuario1.Entity;
				if (((previousValue != value) 
							|| (this._usuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario1.Entity = null;
						previousValue.carrera1.Remove(this);
					}
					this._usuario1.Entity = value;
					if ((value != null))
					{
						value.carrera1.Add(this);
						this._idJefeCarrera = value.idUsuario;
					}
					else
					{
						this._idJefeCarrera = default(Nullable<int>);
					}
					this.SendPropertyChanged("usuario1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="facultad_carrera", Storage="_facultad", ThisKey="idFacultad", OtherKey="idFacultad", IsForeignKey=true)]
		public facultad facultad
		{
			get
			{
				return this._facultad.Entity;
			}
			set
			{
				facultad previousValue = this._facultad.Entity;
				if (((previousValue != value) 
							|| (this._facultad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._facultad.Entity = null;
						previousValue.carrera.Remove(this);
					}
					this._facultad.Entity = value;
					if ((value != null))
					{
						value.carrera.Add(this);
						this._idFacultad = value.idFacultad;
					}
					else
					{
						this._idFacultad = default(Nullable<int>);
					}
					this.SendPropertyChanged("facultad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_alumno(alumno entity)
		{
			this.SendPropertyChanging();
			entity.carrera = this;
		}
		
		private void detach_alumno(alumno entity)
		{
			this.SendPropertyChanging();
			entity.carrera = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.facultad")]
	public partial class facultad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idFacultad;
		
		private string _nombre;
		
		private EntitySet<carrera> _carrera;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidFacultadChanging(int value);
    partial void OnidFacultadChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public facultad()
		{
			this._carrera = new EntitySet<carrera>(new Action<carrera>(this.attach_carrera), new Action<carrera>(this.detach_carrera));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFacultad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idFacultad
		{
			get
			{
				return this._idFacultad;
			}
			set
			{
				if ((this._idFacultad != value))
				{
					this.OnidFacultadChanging(value);
					this.SendPropertyChanging();
					this._idFacultad = value;
					this.SendPropertyChanged("idFacultad");
					this.OnidFacultadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="facultad_carrera", Storage="_carrera", ThisKey="idFacultad", OtherKey="idFacultad")]
		public EntitySet<carrera> carrera
		{
			get
			{
				return this._carrera;
			}
			set
			{
				this._carrera.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrera(carrera entity)
		{
			this.SendPropertyChanging();
			entity.facultad = this;
		}
		
		private void detach_carrera(carrera entity)
		{
			this.SendPropertyChanging();
			entity.facultad = null;
		}
	}
}
#pragma warning restore 1591
