//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceControlEscolar
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usuario", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class usuario : object
    {
        
        private ServiceReferenceControlEscolar.alumno[] alumnoField;
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private ServiceReferenceControlEscolar.carrera[] carreraField;
        
        private ServiceReferenceControlEscolar.carrera[] carrera1Field;
        
        private string correoInstitucionalField;
        
        private int idUsuarioField;
        
        private string matriculaField;
        
        private string nombreField;
        
        private string numeroTelefonicoField;
        
        private string passwordField;
        
        private ServiceReferenceControlEscolar.reporteDeTutoria[] reporteDeTutoriaField;
        
        private string rolField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.alumno[] alumno
        {
            get
            {
                return this.alumnoField;
            }
            set
            {
                this.alumnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.carrera[] carrera
        {
            get
            {
                return this.carreraField;
            }
            set
            {
                this.carreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.carrera[] carrera1
        {
            get
            {
                return this.carrera1Field;
            }
            set
            {
                this.carrera1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoInstitucional
        {
            get
            {
                return this.correoInstitucionalField;
            }
            set
            {
                this.correoInstitucionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroTelefonico
        {
            get
            {
                return this.numeroTelefonicoField;
            }
            set
            {
                this.numeroTelefonicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.reporteDeTutoria[] reporteDeTutoria
        {
            get
            {
                return this.reporteDeTutoriaField;
            }
            set
            {
                this.reporteDeTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="alumno", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class alumno : object
    {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private ServiceReferenceControlEscolar.carrera carreraField;
        
        private string correoField;
        
        private System.Nullable<System.DateTime> fechaNacimientoField;
        
        private ServiceReferenceControlEscolar.Binary fotoField;
        
        private int idAlumnoField;
        
        private System.Nullable<int> idCarreraField;
        
        private System.Nullable<int> idTutorField;
        
        private ServiceReferenceControlEscolar.listaAsistencia[] listaAsistenciaField;
        
        private string matriculaField;
        
        private string nombreField;
        
        private ServiceReferenceControlEscolar.usuario usuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.carrera carrera
        {
            get
            {
                return this.carreraField;
            }
            set
            {
                this.carreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.Binary foto
        {
            get
            {
                return this.fotoField;
            }
            set
            {
                this.fotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAlumno
        {
            get
            {
                return this.idAlumnoField;
            }
            set
            {
                this.idAlumnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCarrera
        {
            get
            {
                return this.idCarreraField;
            }
            set
            {
                this.idCarreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idTutor
        {
            get
            {
                return this.idTutorField;
            }
            set
            {
                this.idTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.listaAsistencia[] listaAsistencia
        {
            get
            {
                return this.listaAsistenciaField;
            }
            set
            {
                this.listaAsistenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.usuario usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="carrera", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class carrera : object
    {
        
        private ServiceReferenceControlEscolar.alumno[] alumnoField;
        
        private string codigoField;
        
        private ServiceReferenceControlEscolar.experienciaEducativa[] experienciaEducativaField;
        
        private ServiceReferenceControlEscolar.facultad facultadField;
        
        private int idCarreraField;
        
        private System.Nullable<int> idCoordinadorTutoriasField;
        
        private System.Nullable<int> idFacultadField;
        
        private System.Nullable<int> idJefeCarreraField;
        
        private string nombreField;
        
        private ServiceReferenceControlEscolar.usuario usuarioField;
        
        private ServiceReferenceControlEscolar.usuario usuario1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.alumno[] alumno
        {
            get
            {
                return this.alumnoField;
            }
            set
            {
                this.alumnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.experienciaEducativa[] experienciaEducativa
        {
            get
            {
                return this.experienciaEducativaField;
            }
            set
            {
                this.experienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.facultad facultad
        {
            get
            {
                return this.facultadField;
            }
            set
            {
                this.facultadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCarrera
        {
            get
            {
                return this.idCarreraField;
            }
            set
            {
                this.idCarreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCoordinadorTutorias
        {
            get
            {
                return this.idCoordinadorTutoriasField;
            }
            set
            {
                this.idCoordinadorTutoriasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idFacultad
        {
            get
            {
                return this.idFacultadField;
            }
            set
            {
                this.idFacultadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idJefeCarrera
        {
            get
            {
                return this.idJefeCarreraField;
            }
            set
            {
                this.idJefeCarreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.usuario usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.usuario usuario1
        {
            get
            {
                return this.usuario1Field;
            }
            set
            {
                this.usuario1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reporteDeTutoria", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class reporteDeTutoria : object
    {
        
        private string comentariosGeneralesField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private int idReporteField;
        
        private System.Nullable<int> idTutorField;
        
        private System.Nullable<int> idTutoriaField;
        
        private ServiceReferenceControlEscolar.listaAsistencia[] listaAsistenciaField;
        
        private System.Nullable<int> numeroSesionField;
        
        private ServiceReferenceControlEscolar.problematicaAcademica[] problematicaAcademicaField;
        
        private ServiceReferenceControlEscolar.tutoria tutoriaField;
        
        private ServiceReferenceControlEscolar.usuario usuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comentariosGenerales
        {
            get
            {
                return this.comentariosGeneralesField;
            }
            set
            {
                this.comentariosGeneralesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReporte
        {
            get
            {
                return this.idReporteField;
            }
            set
            {
                this.idReporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idTutor
        {
            get
            {
                return this.idTutorField;
            }
            set
            {
                this.idTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idTutoria
        {
            get
            {
                return this.idTutoriaField;
            }
            set
            {
                this.idTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.listaAsistencia[] listaAsistencia
        {
            get
            {
                return this.listaAsistenciaField;
            }
            set
            {
                this.listaAsistenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroSesion
        {
            get
            {
                return this.numeroSesionField;
            }
            set
            {
                this.numeroSesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.problematicaAcademica[] problematicaAcademica
        {
            get
            {
                return this.problematicaAcademicaField;
            }
            set
            {
                this.problematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.tutoria tutoria
        {
            get
            {
                return this.tutoriaField;
            }
            set
            {
                this.tutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.usuario usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    public partial class Binary : object
    {
        
        private byte[] BytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes
        {
            get
            {
                return this.BytesField;
            }
            set
            {
                this.BytesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="listaAsistencia", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class listaAsistencia : object
    {
        
        private ServiceReferenceControlEscolar.alumno alumnoField;
        
        private System.Nullable<bool> asistenciaField;
        
        private System.Nullable<int> idEstudianteField;
        
        private int idListaAsistenciaField;
        
        private System.Nullable<int> idReporteTutoriaField;
        
        private ServiceReferenceControlEscolar.reporteDeTutoria reporteDeTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.alumno alumno
        {
            get
            {
                return this.alumnoField;
            }
            set
            {
                this.alumnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> asistencia
        {
            get
            {
                return this.asistenciaField;
            }
            set
            {
                this.asistenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idEstudiante
        {
            get
            {
                return this.idEstudianteField;
            }
            set
            {
                this.idEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idListaAsistencia
        {
            get
            {
                return this.idListaAsistenciaField;
            }
            set
            {
                this.idListaAsistenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idReporteTutoria
        {
            get
            {
                return this.idReporteTutoriaField;
            }
            set
            {
                this.idReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.reporteDeTutoria reporteDeTutoria
        {
            get
            {
                return this.reporteDeTutoriaField;
            }
            set
            {
                this.reporteDeTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="facultad", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class facultad : object
    {
        
        private ServiceReferenceControlEscolar.carrera[] carreraField;
        
        private int idFacultadField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.carrera[] carrera
        {
            get
            {
                return this.carreraField;
            }
            set
            {
                this.carreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFacultad
        {
            get
            {
                return this.idFacultadField;
            }
            set
            {
                this.idFacultadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="experienciaEducativa", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class experienciaEducativa : object
    {
        
        private ServiceReferenceControlEscolar.academico academicoField;
        
        private ServiceReferenceControlEscolar.carrera carreraField;
        
        private System.Nullable<int> idCarreraField;
        
        private int idExperienciaEducativaField;
        
        private System.Nullable<int> idProfesorField;
        
        private string nombreField;
        
        private string nrcField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.academico academico
        {
            get
            {
                return this.academicoField;
            }
            set
            {
                this.academicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.carrera carrera
        {
            get
            {
                return this.carreraField;
            }
            set
            {
                this.carreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCarrera
        {
            get
            {
                return this.idCarreraField;
            }
            set
            {
                this.idCarreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExperienciaEducativa
        {
            get
            {
                return this.idExperienciaEducativaField;
            }
            set
            {
                this.idExperienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProfesor
        {
            get
            {
                return this.idProfesorField;
            }
            set
            {
                this.idProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrc
        {
            get
            {
                return this.nrcField;
            }
            set
            {
                this.nrcField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="academico", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class academico : object
    {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoInstitucionalField;
        
        private ServiceReferenceControlEscolar.experienciaEducativa[] experienciaEducativaField;
        
        private int idAcademicoField;
        
        private string matriculaField;
        
        private string nombreField;
        
        private string numeroTelefonicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoInstitucional
        {
            get
            {
                return this.correoInstitucionalField;
            }
            set
            {
                this.correoInstitucionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.experienciaEducativa[] experienciaEducativa
        {
            get
            {
                return this.experienciaEducativaField;
            }
            set
            {
                this.experienciaEducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAcademico
        {
            get
            {
                return this.idAcademicoField;
            }
            set
            {
                this.idAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroTelefonico
        {
            get
            {
                return this.numeroTelefonicoField;
            }
            set
            {
                this.numeroTelefonicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tutoria", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class tutoria : object
    {
        
        private ServiceReferenceControlEscolar.fechaCierreReporte[] fechaCierreReporteField;
        
        private System.Nullable<System.DateTime> fechaTutoriaField;
        
        private System.Nullable<int> idPeriodoEscolarField;
        
        private int idTutoriaField;
        
        private System.Nullable<int> numeroSesionField;
        
        private ServiceReferenceControlEscolar.periodoEscolar periodoEscolarField;
        
        private ServiceReferenceControlEscolar.reporteDeTutoria[] reporteDeTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.fechaCierreReporte[] fechaCierreReporte
        {
            get
            {
                return this.fechaCierreReporteField;
            }
            set
            {
                this.fechaCierreReporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaTutoria
        {
            get
            {
                return this.fechaTutoriaField;
            }
            set
            {
                this.fechaTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idPeriodoEscolar
        {
            get
            {
                return this.idPeriodoEscolarField;
            }
            set
            {
                this.idPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutoria
        {
            get
            {
                return this.idTutoriaField;
            }
            set
            {
                this.idTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroSesion
        {
            get
            {
                return this.numeroSesionField;
            }
            set
            {
                this.numeroSesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.periodoEscolar periodoEscolar
        {
            get
            {
                return this.periodoEscolarField;
            }
            set
            {
                this.periodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.reporteDeTutoria[] reporteDeTutoria
        {
            get
            {
                return this.reporteDeTutoriaField;
            }
            set
            {
                this.reporteDeTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="problematicaAcademica", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class problematicaAcademica : object
    {
        
        private string categoriaField;
        
        private string descripcionField;
        
        private System.Nullable<System.DateTime> fechaRegistroField;
        
        private int idProblematicaField;
        
        private System.Nullable<int> idReporteTutoriaField;
        
        private System.Nullable<int> numAlumnosField;
        
        private ServiceReferenceControlEscolar.reporteDeTutoria reporteDeTutoriaField;
        
        private ServiceReferenceControlEscolar.solucionProblematica[] solucionProblematicaField;
        
        private string tituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoria
        {
            get
            {
                return this.categoriaField;
            }
            set
            {
                this.categoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaRegistro
        {
            get
            {
                return this.fechaRegistroField;
            }
            set
            {
                this.fechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProblematica
        {
            get
            {
                return this.idProblematicaField;
            }
            set
            {
                this.idProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idReporteTutoria
        {
            get
            {
                return this.idReporteTutoriaField;
            }
            set
            {
                this.idReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numAlumnos
        {
            get
            {
                return this.numAlumnosField;
            }
            set
            {
                this.numAlumnosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.reporteDeTutoria reporteDeTutoria
        {
            get
            {
                return this.reporteDeTutoriaField;
            }
            set
            {
                this.reporteDeTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.solucionProblematica[] solucionProblematica
        {
            get
            {
                return this.solucionProblematicaField;
            }
            set
            {
                this.solucionProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo
        {
            get
            {
                return this.tituloField;
            }
            set
            {
                this.tituloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="solucionProblematica", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class solucionProblematica : object
    {
        
        private string descripcionField;
        
        private System.Nullable<System.DateTime> fechaRegistroField;
        
        private System.Nullable<int> idProblematicaField;
        
        private int idSolucionField;
        
        private ServiceReferenceControlEscolar.problematicaAcademica problematicaAcademicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaRegistro
        {
            get
            {
                return this.fechaRegistroField;
            }
            set
            {
                this.fechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idProblematica
        {
            get
            {
                return this.idProblematicaField;
            }
            set
            {
                this.idProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSolucion
        {
            get
            {
                return this.idSolucionField;
            }
            set
            {
                this.idSolucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.problematicaAcademica problematicaAcademica
        {
            get
            {
                return this.problematicaAcademicaField;
            }
            set
            {
                this.problematicaAcademicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="periodoEscolar", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class periodoEscolar : object
    {
        
        private System.Nullable<System.DateTime> fechaFinField;
        
        private System.Nullable<System.DateTime> fechaInicioField;
        
        private int idPeriodoField;
        
        private string nombreField;
        
        private ServiceReferenceControlEscolar.tutoria[] tutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaFin
        {
            get
            {
                return this.fechaFinField;
            }
            set
            {
                this.fechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaInicio
        {
            get
            {
                return this.fechaInicioField;
            }
            set
            {
                this.fechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPeriodo
        {
            get
            {
                return this.idPeriodoField;
            }
            set
            {
                this.idPeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.tutoria[] tutoria
        {
            get
            {
                return this.tutoriaField;
            }
            set
            {
                this.tutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fechaCierreReporte", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar.Modelo")]
    public partial class fechaCierreReporte : object
    {
        
        private System.Nullable<System.DateTime> fechaInicioField;
        
        private System.Nullable<System.DateTime> fechaLimiteField;
        
        private int idFechaCierreReporteField;
        
        private System.Nullable<int> idTutoriaField;
        
        private ServiceReferenceControlEscolar.tutoria tutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaInicio
        {
            get
            {
                return this.fechaInicioField;
            }
            set
            {
                this.fechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaLimite
        {
            get
            {
                return this.fechaLimiteField;
            }
            set
            {
                this.fechaLimiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFechaCierreReporte
        {
            get
            {
                return this.idFechaCierreReporteField;
            }
            set
            {
                this.idFechaCierreReporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idTutoria
        {
            get
            {
                return this.idTutoriaField;
            }
            set
            {
                this.idTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.tutoria tutoria
        {
            get
            {
                return this.tutoriaField;
            }
            set
            {
                this.tutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar")]
    public partial class Mensaje : object
    {
        
        private bool errorField;
        
        private string messageField;
        
        private ServiceReferenceControlEscolar.usuario usuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceControlEscolar.usuario usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServiciosLinqEscolar")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceControlEscolar.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerUsuarios", ReplyAction="http://tempuri.org/IService1/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.usuario[]> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IniciarSesion", ReplyAction="http://tempuri.org/IService1/IniciarSesionResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.Mensaje> IniciarSesionAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarUsuario", ReplyAction="http://tempuri.org/IService1/GuardarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> GuardarUsuarioAsync(ServiceReferenceControlEscolar.usuario usuarioRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditarUsuario", ReplyAction="http://tempuri.org/IService1/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EditarUsuarioAsync(ServiceReferenceControlEscolar.usuario usuarioEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarUsuario", ReplyAction="http://tempuri.org/IService1/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.CompositeType> GetDataUsingDataContractAsync(ServiceReferenceControlEscolar.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarTutorAcademico", ReplyAction="http://tempuri.org/IService1/GuardarTutorAcademicoResponse")]
        System.Threading.Tasks.Task<bool> GuardarTutorAcademicoAsync(ServiceReferenceControlEscolar.usuario tutorRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEstudiantesPorTutor", ReplyAction="http://tempuri.org/IService1/ObtenerEstudiantesPorTutorResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.alumno[]> ObtenerEstudiantesPorTutorAsync(int idTutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPeriodosEscolares", ReplyAction="http://tempuri.org/IService1/ObtenerPeriodosEscolaresResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.periodoEscolar[]> ObtenerPeriodosEscolaresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerAlumnos", ReplyAction="http://tempuri.org/IService1/obtenerAlumnosResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.alumno[]> obtenerAlumnosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarFechasSesionTutoria", ReplyAction="http://tempuri.org/IService1/RegistrarFechasSesionTutoriaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarFechasSesionTutoriaAsync(string fechaSesion1, string fechaSesion2, string fechaSesion3, int idPeriodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTutores", ReplyAction="http://tempuri.org/IService1/ObtenerTutoresResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.usuario[]> ObtenerTutoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AsignarTutorAlumno", ReplyAction="http://tempuri.org/IService1/AsignarTutorAlumnoResponse")]
        System.Threading.Tasks.Task<bool> AsignarTutorAlumnoAsync(int idAlumno, int idTutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTutoriasPorPeriodoEscolar", ReplyAction="http://tempuri.org/IService1/ObtenerTutoriasPorPeriodoEscolarResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.tutoria[]> ObtenerTutoriasPorPeriodoEscolarAsync(int idPeriodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarFechaCierreATutoriasPeriodoEscolar", ReplyAction="http://tempuri.org/IService1/RegistrarFechaCierreATutoriasPeriodoEscolarResponse")]
        System.Threading.Tasks.Task<bool> RegistrarFechaCierreATutoriasPeriodoEscolarAsync(int idTutoria1, string fechaInicio1, string fechaCierre1, int idTutoria2, string fechaInicio2, string fechaCierre2, int idTutoria3, string fechaInicio3, string fechaCierre3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarFechaCierreVigente", ReplyAction="http://tempuri.org/IService1/VerificarFechaCierreVigenteResponse")]
        System.Threading.Tasks.Task<bool> VerificarFechaCierreVigenteAsync(int idTutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarRegistroReportePorTutoria", ReplyAction="http://tempuri.org/IService1/VerificarRegistroReportePorTutoriaResponse")]
        System.Threading.Tasks.Task<bool> VerificarRegistroReportePorTutoriaAsync(int idTutoria, int idTutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistarListaAsistenciaAReporte", ReplyAction="http://tempuri.org/IService1/RegistarListaAsistenciaAReporteResponse")]
        System.Threading.Tasks.Task<bool> RegistarListaAsistenciaAReporteAsync(int idReporte, int[] idAsistentes, int[] idNoAsistentes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarReporteTutoria", ReplyAction="http://tempuri.org/IService1/RegistrarReporteTutoriaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarReporteTutoriaAsync(string comentariosGenerales, int numeroSesion, int idTutor, int idTutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerReporteCreado", ReplyAction="http://tempuri.org/IService1/ObtenerReporteCreadoResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.reporteDeTutoria> ObtenerReporteCreadoAsync(int idTutoria, int idTutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarProblematicasAcademicas", ReplyAction="http://tempuri.org/IService1/RegistrarProblematicasAcademicasResponse")]
        System.Threading.Tasks.Task<bool> RegistrarProblematicasAcademicasAsync(ServiceReferenceControlEscolar.problematicaAcademica[] listaProblematicas, int idReporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerReportesPorTutor", ReplyAction="http://tempuri.org/IService1/ObtenerReportesPorTutorResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.reporteDeTutoria[]> ObtenerReportesPorTutorAsync(int idTutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerAsistentesPorReporte", ReplyAction="http://tempuri.org/IService1/ObtenerAsistentesPorReporteResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.alumno[]> ObtenerAsistentesPorReporteAsync(int idReporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerNoAsistentesPorReporte", ReplyAction="http://tempuri.org/IService1/ObtenerNoAsistentesPorReporteResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.alumno[]> ObtenerNoAsistentesPorReporteAsync(int idReporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerProblematicasSinSolucion", ReplyAction="http://tempuri.org/IService1/ObtenerProblematicasSinSolucionResponse")]
        System.Threading.Tasks.Task<ServiceReferenceControlEscolar.problematicaAcademica[]> ObtenerProblematicasSinSolucionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ServiceReferenceControlEscolar.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReferenceControlEscolar.IService1>, ServiceReferenceControlEscolar.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.usuario[]> ObtenerUsuariosAsync()
        {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.Mensaje> IniciarSesionAsync(string username, string password)
        {
            return base.Channel.IniciarSesionAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarUsuarioAsync(ServiceReferenceControlEscolar.usuario usuarioRegistro)
        {
            return base.Channel.GuardarUsuarioAsync(usuarioRegistro);
        }
        
        public System.Threading.Tasks.Task<bool> EditarUsuarioAsync(ServiceReferenceControlEscolar.usuario usuarioEdicion)
        {
            return base.Channel.EditarUsuarioAsync(usuarioEdicion);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int idUsuario)
        {
            return base.Channel.EliminarUsuarioAsync(idUsuario);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.CompositeType> GetDataUsingDataContractAsync(ServiceReferenceControlEscolar.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarTutorAcademicoAsync(ServiceReferenceControlEscolar.usuario tutorRegistro)
        {
            return base.Channel.GuardarTutorAcademicoAsync(tutorRegistro);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.alumno[]> ObtenerEstudiantesPorTutorAsync(int idTutor)
        {
            return base.Channel.ObtenerEstudiantesPorTutorAsync(idTutor);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.periodoEscolar[]> ObtenerPeriodosEscolaresAsync()
        {
            return base.Channel.ObtenerPeriodosEscolaresAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.alumno[]> obtenerAlumnosAsync()
        {
            return base.Channel.obtenerAlumnosAsync();
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarFechasSesionTutoriaAsync(string fechaSesion1, string fechaSesion2, string fechaSesion3, int idPeriodoEscolar)
        {
            return base.Channel.RegistrarFechasSesionTutoriaAsync(fechaSesion1, fechaSesion2, fechaSesion3, idPeriodoEscolar);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.usuario[]> ObtenerTutoresAsync()
        {
            return base.Channel.ObtenerTutoresAsync();
        }
        
        public System.Threading.Tasks.Task<bool> AsignarTutorAlumnoAsync(int idAlumno, int idTutor)
        {
            return base.Channel.AsignarTutorAlumnoAsync(idAlumno, idTutor);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.tutoria[]> ObtenerTutoriasPorPeriodoEscolarAsync(int idPeriodoEscolar)
        {
            return base.Channel.ObtenerTutoriasPorPeriodoEscolarAsync(idPeriodoEscolar);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarFechaCierreATutoriasPeriodoEscolarAsync(int idTutoria1, string fechaInicio1, string fechaCierre1, int idTutoria2, string fechaInicio2, string fechaCierre2, int idTutoria3, string fechaInicio3, string fechaCierre3)
        {
            return base.Channel.RegistrarFechaCierreATutoriasPeriodoEscolarAsync(idTutoria1, fechaInicio1, fechaCierre1, idTutoria2, fechaInicio2, fechaCierre2, idTutoria3, fechaInicio3, fechaCierre3);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarFechaCierreVigenteAsync(int idTutoria)
        {
            return base.Channel.VerificarFechaCierreVigenteAsync(idTutoria);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarRegistroReportePorTutoriaAsync(int idTutoria, int idTutor)
        {
            return base.Channel.VerificarRegistroReportePorTutoriaAsync(idTutoria, idTutor);
        }
        
        public System.Threading.Tasks.Task<bool> RegistarListaAsistenciaAReporteAsync(int idReporte, int[] idAsistentes, int[] idNoAsistentes)
        {
            return base.Channel.RegistarListaAsistenciaAReporteAsync(idReporte, idAsistentes, idNoAsistentes);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarReporteTutoriaAsync(string comentariosGenerales, int numeroSesion, int idTutor, int idTutoria)
        {
            return base.Channel.RegistrarReporteTutoriaAsync(comentariosGenerales, numeroSesion, idTutor, idTutoria);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.reporteDeTutoria> ObtenerReporteCreadoAsync(int idTutoria, int idTutor)
        {
            return base.Channel.ObtenerReporteCreadoAsync(idTutoria, idTutor);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarProblematicasAcademicasAsync(ServiceReferenceControlEscolar.problematicaAcademica[] listaProblematicas, int idReporte)
        {
            return base.Channel.RegistrarProblematicasAcademicasAsync(listaProblematicas, idReporte);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.reporteDeTutoria[]> ObtenerReportesPorTutorAsync(int idTutor)
        {
            return base.Channel.ObtenerReportesPorTutorAsync(idTutor);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.alumno[]> ObtenerAsistentesPorReporteAsync(int idReporte)
        {
            return base.Channel.ObtenerAsistentesPorReporteAsync(idReporte);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.alumno[]> ObtenerNoAsistentesPorReporteAsync(int idReporte)
        {
            return base.Channel.ObtenerNoAsistentesPorReporteAsync(idReporte);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceControlEscolar.problematicaAcademica[]> ObtenerProblematicasSinSolucionAsync()
        {
            return base.Channel.ObtenerProblematicasSinSolucionAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57866/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
